### ISSUE TITLE
Error with ppx_deriving when installing nanomq

### ISSUE THREAD

**Issue by sapristi** [whitequark/ppx_deriving#67] opened 2015-12-28 17:04 UTC
Incompatibiliy between Ppx_deriving_runtime.string and string when installing nanomq

```
#=== ERROR while installing nanomsg.1.0 =======================================#
# opam-version 1.2.2
# os           linux
# command      ocaml pkg/build.ml native=true native-dynlink=true lwt=true ounit=true
# path         /home/sapristi/.opam/system/build/nanomsg.1.0
# compiler     system (4.02.3)
# exit-code    10
# env-file     /home/sapristi/.opam/system/build/nanomsg.1.0/nanomsg-13706-ad8886.env
# stdout-file  /home/sapristi/.opam/system/build/nanomsg.1.0/nanomsg-13706-ad8886.out
# stderr-file  /home/sapristi/.opam/system/build/nanomsg.1.0/nanomsg-13706-ad8886.err
### stdout ###
# [...]
# ocamlfind ocamlc -c -g -bin-annot -safe-string -package containers.bigarray -package ipaddr -package containers -package lwt.unix -package lwt.ppx -package ctypes -package ppx_deriving.std -I lib -I lib_test -o lib/nanomsg_lwt.cmi lib/nanomsg_lwt.mli
# ocamlfind ocamlc -c -g -bin-annot -safe-string -package containers.bigarray -package ctypes.foreign -package ipaddr -package containers -package lwt.unix -package lwt.ppx -package oUnit -I lib_test -I lib -o lib_test/suite.cmo lib_test/suite.ml
# + ocamlfind ocamlc -c -g -bin-annot -safe-string -package containers.bigarray -package ctypes.foreign -package ipaddr -package containers -package lwt.unix -package lwt.ppx -package oUnit -I lib_test -I lib -o lib_test/suite.cmo lib_test/suite.ml
# File "lib_test/suite.ml", line 29, characters 13-40:
# Error: This expression has type
#          Nanomsg.Addr.connect Nanomsg.Addr.t -> Ppx_deriving_runtime.string
#        but an expression was expected of type
#          Nanomsg.Addr.connect Nanomsg.Addr.t -> string
#        Type Ppx_deriving_runtime.string is not compatible with type string 
# Command exited with code 2.```

**Comment by whitequark** [comment] 2015-12-28 17:08
That's bizarre--why wouldn't it be? https://github.com/whitequark/ppx_deriving/blob/master/src/ppx_deriving_runtime.mli#L29

**Comment by rgrinberg** [comment] 2015-12-28 17:17
This is fixed in nanomsg/master I believe. I think @vbmithr fixed so I'm not sure what was the cause.

**Comment by sapristi** [comment] 2015-12-28 17:23
so I should install from github and not through opam ?

**Comment by rgrinberg** [comment] 2015-12-28 17:24
`$ opam pin add nanomsg --dev-repo` should be ok but keep in mind that there's some bugs outstanding in master for now. I'm working on them this week however.

**Comment by sapristi** [comment] 2015-12-28 17:33
ok thanks !

**Comment by whitequark** [comment] 2016-01-27 23:14
Closing as it is fixed upstream.

**Closed by whitequark** 2016-01-27 23:14 UTC
